# Numpy 다루기

## Numpy 배열 다루기
- 파이썬의 Numpy 패키지는 데이터 분석과 산술 연산에 사용하는 기본적인 패키지 중 하나
- 다차원배열을 정의하고 처리하는데 필요한 다양한 기능을 제공

### Numpy 개요
- 행렬이나 대규모 다차원배열을 쉽게 처리하도록 도와주는 파이썬 패키지로 많은 머신러닝, 딥러닝 패키지가 넘파이를 기반으로 구현
- 파이썬에서 기본 제공되는 리스트 자료구조와 유사하지만, 배열의 크기가 커져도 높은 성능을 보장하며 배열을 이용한 다양한 통계, 수학 함수도 제공한다(파이썬 리스트는 배열의 크기가 커질수록 성능이 떨어짐)
- 동일한 자료형만 담을 수 있다(리스트는 다양한 자료형 가능)

In [4]:
# numpy 패키지 설치
# !pip install numpy

In [5]:
# numpy 패키지 추가
import numpy as np

### ndarray 객체
- ndarray는 넘파이 패키지에 있는 다차원 배열을 지원하는 객체
- ndarray 객체는 리스트와 유사한 구조로 배열을 표현하지만, 리스트보다 다양한 기능을 제공
- 다양한 메소드를 제공하며 다차원 배열을 정의하고 사용

In [ ]:
# 배열 만들기 및 초기화

ar1 = np.array([1, 2, 3, 4, 5])
ar2 = np.array([[1, 2, 3], [4, 5, 6]])

print("ar1 = ")
print(ar1)
print("=======")
print("ar2 = ")
print(ar2)

ar1 = 
[1 2 3 4 5]
ar2 = 
[[1 2 3]
 [4 5 6]]


In [ ]:
# 난수를 이용한 2차원 배열 객체 생성

ar3 = np.random.randn(3) # 3 크기의 1차원 배열을 생성(난수 발생)
ar4 = np.random.randn(2, 3) # 2*3 크기의 2차원 배열 생성(난수 발생)

print("ar3 = ")
print(ar3)
print("=======")
print("ar4 = ")
print(ar4)

ar1 = 
[-2.55773403 -0.00953126  1.29557603]
ar2 = 
[[ 0.68126664 -0.56890839  0.24505744]
 [ 1.08493224 -0.0577288  -0.067125  ]]


In [12]:
# 원소를 0 또는 1로 초기화

ar5 = np.zeros(5) # 1차원 배열 [0, 0, 0, 0, 0] 생성
ar6 = np.ones((2, 3)) # 2차원 배열([1, 1, 1], [1, 1, 1]) 생성

print("ar5 = ")
print(ar5)
print("=======")
print("ar6 = ")
print(ar6)

ar5 = 
[0. 0. 0. 0. 0.]
ar6 = 
[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# arrange()와 reshape() 메소드 사용

ar7 = np.arange(20, 200, 10) # 20부터 200-1까지 10씩 증가
ar8 = ar7.reshape(3, 6) # 3*6 배열로 재배치

print("ar7 = ")
print(ar7)
print("=======")
print("ar8 = ")
print(ar8)

ar7 = 
[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
ar8 = 
[[ 20  30  40  50  60  70]
 [ 80  90 100 110 120 130]
 [140 150 160 170 180 190]]


In [ ]:
ar7 = np.arange(20, 200, 10)
ar8 = ar7.reshape(3, 5)

# reshape을 할 경우 사이즈가 안맞으면 불가능능

ValueError: cannot reshape array of size 18 into shape (3,5)

### 배열 다루기
- 인덱스를 이용하여 원하는 위치의 배열 원소값을 읽어오거나 값을 변경

In [25]:
# 인덱스를 이용하여 원하는 위치의 배열 원소값을 읽어오거나 값을 변경

ar1 = np.arange(1, 21, 1)
print(ar1)
print(ar1[1])

print("======")

ar2 = ar1.reshape(2, 10)
print(ar2)

print("======")

ar2[1][1] = 100
print(ar2)
print(ar2[1][0], ar2[1][1], ar2[1][2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11 100  13  14  15  16  17  18  19  20]]
11 100 13


In [27]:
# 배열의 산술 연산 : 배열의 연산은 배열 원소에 각각 적용
ar1 = np.arange(1, 11, 1)
ar2 = ar1 + 3
ar3 = ar1 * 2
print(ar1)
print(ar2, "\n", ar3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10 11 12 13] 
 [ 2  4  6  8 10 12 14 16 18 20]


In [28]:
# 배열의 통계 메소드 사용

ar1 = np.array([[5, 7, 9], [-7, -6, 19], [6, 9, 11]])
print(ar1)
print(ar1.sum())
print(ar1.mean())
print(ar1.max())
print(ar1.min())
print(ar1.max(axis=0))
print(ar1.max(axis=1))


[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7
[ 6  9 19]
[ 9 19 11]


In [ ]:
# 조건식을 사용한 연산

ar1 = np.array([[5, 7, 9], [-7, -6, 19], [6, 9, 11]])
print(ar1 > 0) # ar1의 각 원소가 0보다 큰지 판단한 결과를 출력
m_count = (ar1 < 0).sum() # 원소 중 음수가 몇 개 인지 계산산
print(m_count)

# ar1의 원소가 0보다 작으면 ar2를 0으로 변경, 그렇지 않으면 ar1의 값으로 대입
ar2 = np.where(ar1 < 0, 0, ar1)
print(ar2)

[[ True  True  True]
 [False False  True]
 [ True  True  True]]
2
[[ 5  7  9]
 [ 0  0 19]
 [ 6  9 11]]


In [ ]:
# 배열의 정렬

ar1 = np.array([[5, 7, 9], [-3, -6, 19], [6, 4, 11]])
print(ar1)

ar1.sort(0) # sort(0)는 열 단위로 원소를 정렬
print(ar1)

ar1.sort(1) # sort(1)는 행 단위로 원소를 정렬렬
print(ar1)

[[ 5  7  9]
 [-3 -6 19]
 [ 6  4 11]]
[[-3 -6  9]
 [ 5  4 11]
 [ 6  7 19]]
[[-6 -3  9]
 [ 4  5 11]
 [ 6  7 19]]
